FROM ubuntubase

RUN ["/bin/bash", "-c", "apt-get install  libxerces-c3.1 libxerces-c-dev libicu-dev build-essential -y"]
RUN ["/bin/bash", "-c", "apt-get install  emacs emacs-goodies* git git-extras screen -y"]


