# -*- mode: ruby -*-
# vi: set ft=ruby :

variables = %w{AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY}
missing = variables.find_all { |v| ENV[v] == nil }
unless missing.empty?
  puts "FATAL: #{missing.join(', ')}."
  exit
end

Vagrant::Config.run do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network :hostonly, "192.168.50.4"
  config.vm.provision "shell", inline: "mkdir ~/.aws && cp /vagrant/aws_config ~/.aws/config"
  config.vm.provision "shell", inline: "echo [default] >> ~/.aws/credentials"
  config.vm.provision "shell", inline: "echo aws_access_key_id=#{ENV['AWS_ACCESS_KEY_ID']} >>  ~/.aws/credentials"
  config.vm.provision "shell", inline: "echo aws_secret_access_key=#{ENV['AWS_SECRET_ACCESS_KEY']} >>  ~/.aws/credentials"
  config.vm.provision "shell", inline: "cp /vagrant/aws_config ~/.aws/config"
  config.vm.provision "shell", path: "mysql.sh"
  config.vm.provision "shell", path: "aws.sh"
  config.vm.provision "shell", path: "aws_mysql.sh"
end
